### ISSUE TITLE
Error: function JOSE.JWT.from_map/1 is undefined (module JOSE.JWT is not available)

### ISSUE THREAD

**Issue by tfwright** [tuvistavie/elixir-web-push-encryption#12]
I'm getting this error when trying to call `send_web_push` with a simple test payload:

```
payload = %{title: "test"} |> Jason.encode! 

sub = %{
  endpoint: "https://fcm.googleapis.com/fcm/send/[some id]",
  expiration_time: nil,
  keys: %{
    auth: "[key]",
    p256dh: "[key]"
  }
}

WebPushEncryption.send_web_push(payload, sub)
```

Error:

```
** (UndefinedFunctionError) function JOSE.JWT.from_map/1 is undefined (module JOSE.JWT is not available)
    JOSE.JWT.from_map(%{aud: "https://fcm.googleapis.com", exp: 1556343721, sub: nil})
    (web_push_encryption) lib/web_push_encryption/vapid.ex:18: WebPushEncryption.Vapid.get_headers/4
    (web_push_encryption) lib/web_push_encryption/push.ex:34: WebPushEncryption.Push.send_web_push/3
```

From `mix.lock`:

```
"jose": {:hex, :jose, "1.9.0", "4167c5f6d06ffaebffd15cdb8da61a108445ef5e85ab8f5a7ad926fdf3ada154", [:mix, :rebar3], [{:base64url, "~> 0.0.1", [hex: :base64url, repo: "hexpm", optional: false]}], "hexpm"},
...
"web_push_encryption": {:hex, :web_push_encryption, "0.2.1", "d42cecf73420d9dc0053ba3299cc8c8d6ff2be2487d67ca2a57265868e4d9a98", [:mix], [{:httpoison, "~> 1.0", [hex: :httpoison, repo: "hexpm", optional: false]}, {:jose, "~> 1.8", [hex: :jose, repo: "hexpm", optional: false]}, {:poison, "~> 3.0", [hex: :poison, repo: "hexpm", optional: false]}], "hexpm"},

```

Any ideas? Thanks!

**Comment by tfwright** [comment]
Also, I probably should have mentioned that I am fairly new to Elixir, so apologies if some minor stupidity on my part is the issue. I'm still troubleshooting, but I don't understand why that module wouldn't be available in my app.

**Comment by tfwright** [comment]
Looks like this was me! This issue was already fixed in master here: https://github.com/danhper/elixir-web-push-encryption/commit/4d4047dfa4f8cb83de77705ed195b74a597ee78d

If you have some time to release a new version, it would be much appreciated!

**Comment by danhper** [comment]
Great, I'll close then. Please feel free to comment or open a new issue if you still run into problems.
